---
name: Release to Ansible Galaxy

on:
  workflow_call:
    secrets:
      galaxy_api_key:
        required: true

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.2.1
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}
          git_branch: ${{ github.event.repository.default_branch }}
