---

name: Release Ansible role to Ansible Galaxy

on:
  workflow_call:
    secrets:
      galaxy_api_key:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.galaxy_api_key }}
          --branch ${{ github.event.repository.default_branch }}
          $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
