---
name: Create Semantic Release

on:
  workflow_call:
    secrets:
      ADFINISBOT_GITHUB_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1.23
        with:
          allow-initial-development-versions: true
          github-token: ${{ secrets.ADFINISBOT_GITHUB_TOKEN }}
          custom-arguments: "--provider-opt='strip_v_tag_prefix=true'"
