---
name: Create Semantic Release

on:
  workflow_call:
    secrets:
      ADFINIS_RELEASES_GITHUB_CLIENT_ID:
        required: true
      ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.ADFINIS_RELEASES_GITHUB_CLIENT_ID }}
          private-key: ${{ secrets.ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@2e9dc4247a6004f8377781bef4cb9dad273a741f # v1.24.1
        with:
          allow-initial-development-versions: true
          github-token: ${{ steps.app-token.outputs.token }}
