---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: adfinis/github-workflows-bareos/blob/main/.github/workflows/ansible-role.yaml@main
    secrets:
      ADFINISBOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
