---
# runs on each push to main and is responsible for creating new tags/releases
name: Create Semantic Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    uses: ./.github/workflows/semantic-release.yaml
    secrets:
      ADFINIS_RELEASES_GITHUB_CLIENT_ID: ${{ secrets.ADFINIS_RELEASES_GITHUB_CLIENT_ID }}
      ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY: ${{ secrets.ADFINIS_RELEASES_GITHUB_APP_PRIVATE_KEY }}
